image: docker.10up.com/10up-build/deploy-container:latest

stages:
  - test
  - deploy

# Define paths that should be cached between jobs. Good use cases are things like node_modules_cache and .composer-cache
cache:
  paths:
    - .composer-cache # Composer
    - node_modules_cache

test:
  stage: test
  script:
    - 10up-scripts

deploy_stage:
  stage: deploy
  environment:
    name: Staging
    url: https://bbgistage.com/
  script:
    - bash ./deploy-scripts/build.sh
    - bash ./deploy-scripts/deploy-stage.sh
    - ssh beanstalk@54.87.4.54 'sudo /usr/bin/systemctl restart supervisord.service'
    - ssh beanstalk@54.87.4.54 'sudo /usr/bin/systemctl restart memcached.service'
    - ssh beanstalk@54.87.4.54 'echo $(date +%s) > /var/www/html/wordpress/wp-content/themes/.version.php'
  only:
    - stage

deploy_prod:
  stage: deploy
  environment:
    name: Production
    url: https://sites.greatermedia.com/
  script:
    - bash ./deploy-scripts/build.sh
    # preprod should always be up to date with production
    - bash ./deploy-scripts/deploy-preprod.sh
    - bash ./deploy-scripts/deploy-prod.sh
    - bash ./deploy-scripts/sync-jobs-to-web.sh # Sync all code first, before updating version timestamp to avoid cache issues
    - ssh beanstalk@52.0.13.41 'echo $(date +%s) > /var/www/html/wordpress/wp-content/themes/.version.php'
    - bash ./deploy-scripts/sync-jobs-to-web.sh # Sync code again, with updated version timestamp (Should only update the .version)
  only:
    - master
  when: manual
  allow_failure: false
