image: docker.10up.com/10up-build/deploy-container:php-7.4

stages:
  - test-and-build
  - deploy
  - post-deploy

# Define paths that should be cached between jobs. Good use cases are things like node_modules_cache and .composer-cache
cache:
  paths:
    - .composer-cache # Composer
    - node_modules_cache

# run tests in parallel for performance

# customize the 10up php syntax check to avoid the archive theme folder
# https://gitlab.10up.com/10up-build/deploy-container/-/blob/master/scripts/10up-scripts

test_syntax:
  stage: test-and-build
  script:
    - find . -type f -name '*.php' -not -path '*/vendor/*' -not -path '*/archive-themes-nodeploy/*' -print0 | xargs -0 -n1 php -l
  dependencies: []
  cache: {}

test_virusscan:
  stage: test-and-build
  script:
    - virus-scan
  dependencies: []
  cache: {}

build_plugins_and_themes:
  stage: test-and-build
  script:
    - bash ./deploy-scripts/build.sh
  artifacts:
    paths:
      - payload
    expire_in: 1 day
  dependencies: []
  cache: {}


deploy_stage:
  stage: deploy
  environment:
    name: Staging
    url: https://bbgistage.com/
  script:
    - bash ./deploy-scripts/deploy-stage.sh
    - ssh beanstalk@54.87.4.54 'sudo /usr/bin/systemctl restart supervisord.service'
    - ssh beanstalk@54.87.4.54 'sudo /usr/bin/systemctl restart memcached.service'
    - ssh beanstalk@54.87.4.54 'echo $(date +%s) > /var/www/html/wordpress/wp-content/themes/.version.php'
  only:
    - stage3

deploy_preprod:
  stage: deploy
  environment:
    name: Preprod
    url: https://preprod.bbgistage.com/
  script:
    - bash ./deploy-scripts/deploy-preprod.sh
    - ssh beanstalk@34.230.103.178 'sudo /usr/bin/systemctl restart supervisord.service'
    - ssh beanstalk@34.230.103.178 'sudo /usr/bin/systemctl restart memcached.service'
    - ssh beanstalk@34.230.103.178 'echo $(date +%s) > /var/www/html/wordpress/wp-content/themes/.version.php'
  only:
    - preprod

notify_slack:
  stage: test-and-build
  script:
    - curl -X POST --data "{\"username\":\"Gitlab Pipeline\", \"text\":\"Gitlab pipeline is about to run the Production Deployment..\"}" $SLACK_WEBHOOK
  only:
    - master

deploy_prod:
  stage: deploy
  environment:
    name: Production
    url: https://sites.greatermedia.com/
  script:
    - bash ./deploy-scripts/deploy-prod.sh
    - bash ./deploy-scripts/sync-jobs-to-web.sh # Sync all code first, before updating version timestamp to avoid cache issues
    - ssh beanstalk@52.0.13.41 'echo $(date +%s) > /var/www/html/wordpress/wp-content/themes/.version.php'
    - bash ./deploy-scripts/sync-jobs-to-web.sh # Sync code again, with updated version timestamp (Should only update the .version)
  only:
    - master
  when: manual
  allow_failure: false

cloudflare_purge_desktop:
  stage: post-deploy
  script:
    - bash ./deploy-scripts/purge-cf-cache.sh desktop
  only:
    - stage3
    - master
  when: manual
  allow_failure: false

cloudflare_purge_content:
  stage: post-deploy
  script:
    - bash ./deploy-scripts/purge-cf-cache.sh content
  only:
    - stage3
    - master
  when: manual
  allow_failure: false

cloudflare_purge_mobile:
  stage: post-deploy
  script:
    - bash ./deploy-scripts/purge-cf-cache.sh mobile
  only:
    - stage3
    - master
  when: manual
  allow_failure: false
